<?php
/**
 * An helper file for your Eloquent Models
 * Copy the phpDocs from this file to the correct Model,
 * And remove them from this file, to prevent double declarations.
 *
 * @author Barry vd. Heuvel <barryvdh@gmail.com>
 */


namespace App\Models{
/**
 * App\Models\Agent
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $last_updated
 * @property \Carbon\Carbon $deleted_at
 * @property string $org_email
 * @property string $org_name
 * @property string $ind_affiliation
 * @property string $ind_role
 * @property string $address1
 * @property string $address2
 * @property string $city
 * @property string $state
 * @property string $postal_code
 * @property string $country
 * @property string $phone
 * @property string $web_address
 * @property string $type
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Profile[] $Profiles
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $Users
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Schema[] $Schemas
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Vocabulary[] $Vocabularies
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereLastUpdated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereOrgEmail($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereOrgName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereIndAffiliation($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereIndRole($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereAddress1($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereAddress2($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereCity($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereState($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent wherePostalCode($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereCountry($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent wherePhone($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereWebAddress($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Agent whereType($value)
 */
	class Agent {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_agent_has_user table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property string $created_at
 * @property string $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $user_id
 * @property integer $agent_id
 * @property boolean $is_registrar_for
 * @property boolean $is_admin_for
 * @property-read \App\Models\User $User
 * @property-read \App\Models\Agent $Agent
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereAgentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereIsRegistrarFor($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\AgentHasUser whereIsAdminFor($value)
 */
	class AgentHasUser {}
}

namespace App\Models{
/**
 * Eloquent class to describe the arc_g2t table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $g
 * @property integer $t
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcG2t whereG($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcG2t whereT($value)
 */
	class ArcG2t {}
}

namespace App\Models{
/**
 * Eloquent class to describe the arc_id2val table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property boolean $misc
 * @property string $val
 * @property boolean $val_type
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcId2val whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcId2val whereMisc($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcId2val whereVal($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcId2val whereValType($value)
 */
	class ArcId2val {}
}

namespace App\Models{
/**
 * Eloquent class to describe the arc_o2val table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property integer $cid
 * @property boolean $misc
 * @property string $val
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcO2val whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcO2val whereCid($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcO2val whereMisc($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcO2val whereVal($value)
 */
	class ArcO2val {}
}

namespace App\Models{
/**
 * Eloquent class to describe the arc_s2val table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property integer $cid
 * @property boolean $misc
 * @property string $val
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcS2val whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcS2val whereCid($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcS2val whereMisc($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcS2val whereVal($value)
 */
	class ArcS2val {}
}

namespace App\Models{
/**
 * Eloquent class to describe the arc_setting table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property string $k
 * @property string $val
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcSetting whereK($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcSetting whereVal($value)
 */
	class ArcSetting {}
}

namespace App\Models{
/**
 * Eloquent class to describe the arc_triple table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $t
 * @property integer $s
 * @property integer $p
 * @property integer $o
 * @property integer $o_lang_dt
 * @property string $o_comp
 * @property boolean $s_type
 * @property boolean $o_type
 * @property boolean $misc
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereT($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereS($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereP($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereO($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereOLangDt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereOComp($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereSType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereOType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcTriple whereMisc($value)
 */
	class ArcTriple {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_batch table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property \Carbon\Carbon $run_time
 * @property string $run_description
 * @property string $object_type
 * @property integer $object_id
 * @property \Carbon\Carbon $event_time
 * @property string $event_type
 * @property string $event_description
 * @property string $registry_uri
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\FileImportHistory[] $FileImportHistory
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereRunTime($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereRunDescription($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereObjectType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereObjectId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereEventTime($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereEventType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereEventDescription($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Batch whereRegistryUri($value)
 */
	class Batch {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_collection table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property string $created_at
 * @property string $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property \Carbon\Carbon $last_updated
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property integer $vocabulary_id
 * @property string $name
 * @property string $uri
 * @property string $pref_label
 * @property integer $status_id
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @property-read \App\Models\Status $Status
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereLastUpdated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection wherePrefLabel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Collection whereStatusId($value)
 */
	class Collection {}
}

namespace App\Models{
/**
 * App\Models\Concept
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property \Carbon\Carbon $last_updated
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property string $uri
 * @property string $pref_label
 * @property integer $vocabulary_id
 * @property boolean $is_top_concept
 * @property integer $pref_label_id
 * @property integer $status_id
 * @property string $language
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\ConceptProperty $PrefLabelConceptProperty
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\Status $Status
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $ConceptProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $RelatedConceptProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $RelatedConceptPropertyHistories
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistories
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $Discussions
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereLastUpdated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept wherePrefLabel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereIsTopConcept($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept wherePrefLabelId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Concept whereLanguage($value)
 */
	class Concept {}
}

namespace App\Models{
/**
 * App\Models\ConceptProperty
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property \Carbon\Carbon $last_updated
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property integer $concept_id
 * @property boolean $primary_pref_label
 * @property integer $skos_property_id
 * @property string $object
 * @property integer $scheme_id
 * @property integer $related_concept_id
 * @property string $language
 * @property integer $status_id
 * @property boolean $is_concept_property
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\Concept $Concept
 * @property-read \App\Models\ProfileProperty $profileProperty
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @property-read \App\Models\Status $Status
 * @property-read \App\Models\Concept $RelatedConcept
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Concept[] $PrefLabelConcept
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistories
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $Discussions
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereLastUpdated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereConceptId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty wherePrimaryPrefLabel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereSkosPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereObject($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereSchemeId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereRelatedConceptId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptProperty whereIsConceptProperty($value)
 */
	class ConceptProperty {}
}

namespace App\Models{
/**
 * App\Models\ConceptPropertyHistory
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property string $action
 * @property integer $concept_property_id
 * @property integer $concept_id
 * @property integer $vocabulary_id
 * @property integer $skos_property_id
 * @property string $object
 * @property integer $scheme_id id of the related vocabulary when required
 * @property integer $related_concept_id id of the related concept when required
 * @property string $language This will be an RFC3066 language code, which means it can be en, eng, en-us, or eng-us -- iso639-1 (2-char codes), iso639-2 (3-char codes), and combined with iso3166 (2-char country codes)
 * @property integer $status_id
 * @property integer $created_user_id The ID of the user that created the property
 * @property string $change_note
 * @property integer $import_id
 * @property-read \App\Models\SkosProperty $SkosProperty
 * @property-read \App\Models\FileImportHistory $FileImportHistory
 * @property-read \App\Models\Vocabulary $ObjectScheme
 * @property-read \App\Models\Status $Status
 * @property-read \App\Models\Concept $ObjectConcept
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\ConceptProperty $ConceptProperty
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @property-read \App\Models\Concept $Concept
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereAction($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereConceptPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereConceptId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereSkosPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereObject($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereSchemeId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereRelatedConceptId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereChangeNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ConceptPropertyHistory whereImportId($value)
 */
	class ConceptPropertyHistory {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_discuss table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property string $created_at
 * @property string $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_user_id
 * @property integer $deleted_user_id
 * @property string $uri
 * @property integer $schema_id
 * @property integer $schema_property_id
 * @property integer $schema_property_element_id
 * @property integer $vocabulary_id
 * @property integer $concept_id
 * @property integer $concept_property_id
 * @property integer $root_id
 * @property integer $parent_id
 * @property string $subject
 * @property string $content
 * @property-read \App\Models\User $UserCreayed
 * @property-read \App\Models\ConceptProperty $ConceptProperty
 * @property-read \App\Models\User $UserDeletor
 * @property-read \App\Models\Schema $Schema
 * @property-read \App\Models\SchemaProperty $SchemaProperty
 * @property-read \App\Models\SchemaPropertyElement $SchemaPropertyElement
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @property-read \App\Models\Concept $Concept
 * @property-read \App\Models\Discuss $DiscussRoot
 * @property-read \App\Models\Discuss $DiscussParent
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereDeletedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereSchemaId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereSchemaPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereSchemaPropertyElementId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereConceptId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereConceptPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereRootId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereParentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereSubject($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Discuss whereContent($value)
 */
	class Discuss {}
}

namespace App\Models{
/**
 * App\Models\Element
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property integer $schema_id
 * @property string $name
 * @property string $label
 * @property string $definition
 * @property string $comment
 * @property string $type
 * @property integer $is_subproperty_of
 * @property string $parent_uri
 * @property string $uri
 * @property integer $status_id
 * @property string $language
 * @property string $note
 * @property string $domain
 * @property string $orange
 * @property boolean $is_deprecated Boolean. Has this class/property been deprecated
 * @property string $url
 * @property string $lexical_alias
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\Schema $Schema
 * @property-read \App\Models\SchemaProperty $SchemaProperty
 * @property-read \App\Models\Status $Status
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $Discussions
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaProperty[] $ParentElements
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElement[] $Properties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElement[] $RelatedElements
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $History
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $ObjectHistory
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereSchemaId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereLabel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereDefinition($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereComment($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereIsSubpropertyOf($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereParentUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereDomain($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereOrange($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereIsDeprecated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereUrl($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Element whereLexicalAlias($value)
 */
	class Element {}
}

namespace App\Models{
/**
 * App\Models\ElementProperty
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property integer $schema_property_id
 * @property integer $profile_property_id
 * @property boolean $is_schema_property
 * @property string $object
 * @property integer $related_schema_property_id
 * @property string $language
 * @property integer $status_id
 * @property boolean $is_generated
 * @property-read \App\Models\ProfileProperty $profileProperty
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\SchemaProperty $SchemaProperty
 * @property-read \App\Models\SchemaProperty $RelatedSchemaProperty
 * @property-read \App\Models\Status $Status
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $Discussions
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $History
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereSchemaPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereProfilePropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereIsSchemaProperty($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereObject($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereRelatedSchemaPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementProperty whereIsGenerated($value)
 */
	class ElementProperty {}
}

namespace App\Models{
/**
 * App\Models\ElementPropertyHistory
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property integer $created_user_id
 * @property string $action
 * @property integer $schema_property_element_id
 * @property integer $schema_property_id
 * @property integer $schema_id
 * @property integer $profile_property_id
 * @property string $object
 * @property integer $related_schema_property_id
 * @property string $language
 * @property integer $status_id
 * @property string $change_note
 * @property integer $import_id
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\SchemaPropertyElement $SchemaPropertyElement
 * @property-read \App\Models\SchemaProperty $SchemaProperty
 * @property-read \App\Models\Schema $Schema
 * @property-read \App\Models\SchemaProperty $RelatedSchemaProperty
 * @property-read \App\Models\Status $Status
 * @property-read \App\Models\ProfileProperty $profileProperty
 * @property-read \App\Models\FileImportHistory $FileImportHistory
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereAction($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereSchemaPropertyElementId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereSchemaPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereSchemaId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereProfilePropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereObject($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereRelatedSchemaPropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereChangeNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementPropertyHistory whereImportId($value)
 */
	class ElementPropertyHistory {}
}

namespace App\Models{
/**
 * App\Models\ElementSet
 *
 * @property integer $id
 * @property integer $agent_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property string $child_updated_at
 * @property integer $child_updated_user_id
 * @property string $name
 * @property string $note
 * @property string $uri
 * @property string $url
 * @property string $base_domain
 * @property string $token
 * @property string $community
 * @property integer $last_uri_id
 * @property integer $status_id
 * @property string $language
 * @property integer $profile_id
 * @property string $ns_type
 * @property string $prefixes
 * @property string $languages
 * @property string $repo
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereAgentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereChildUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereChildUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereUrl($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereBaseDomain($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereCommunity($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereLastUriId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereProfileId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereNsType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet wherePrefixes($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereLanguages($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ElementSet whereRepo($value)
 */
	class ElementSet {}
}

namespace App\Models{
/**
 * App\Models\FileImportHistory
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property string $map stores the serialized column map array
 * @property integer $user_id
 * @property integer $vocabulary_id
 * @property integer $schema_id
 * @property string $file_name
 * @property string $source_file_name
 * @property string $file_type
 * @property integer $batch_id
 * @property string $results stores the serialized results of the import
 * @property integer $total_processed_count
 * @property integer $error_count
 * @property integer $success_count
 * @property-read \App\Models\User $User
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @property-read \App\Models\Schema $Schema
 * @property-read \App\Models\Batch $Batch
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistory
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $ElementPropertyHistory
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereMap($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereSchemaId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereFileName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereSourceFileName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereFileType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereBatchId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereResults($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereTotalProcessedCount($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereErrorCount($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\FileImportHistory whereSuccessCount($value)
 */
	class FileImportHistory {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_lookup table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property integer $type_id This will be the lookup type and will reference the list of lookup types stored in this very same table
 * @property string $short_value
 * @property string $long_value
 * @property integer $display_order
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Lookup whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Lookup whereTypeId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Lookup whereShortValue($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Lookup whereLongValue($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Lookup whereDisplayOrder($value)
 */
	class Lookup {}
}

namespace App\Models{
/**
 * App\Models\Prefix
 *
 * @property string $prefix
 * @property string $uri
 * @property integer $rank
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Prefix wherePrefix($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Prefix whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Prefix whereRank($value)
 */
	class Prefix {}
}

namespace App\Models{
/**
 * App\Models\Profile
 *
 * @property integer $id
 * @property integer $agent_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $deleted_by
 * @property string $child_updated_at
 * @property integer $child_updated_by
 * @property string $name
 * @property string $note
 * @property string $uri
 * @property string $url
 * @property string $base_domain
 * @property string $token
 * @property string $community
 * @property integer $last_uri_id
 * @property integer $status_id
 * @property string $language
 * @property-read \App\Models\Agent $Agent
 * @property-read \App\Models\Status $Status
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserDeletor
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProfileProperty[] $profileProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Schema[] $Schemas
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Vocabulary[] $Vocabularies
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereAgentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereCreatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereUpdatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereDeletedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereChildUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereChildUpdatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereUrl($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereBaseDomain($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereCommunity($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereLastUriId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Profile whereLanguage($value)
 */
	class Profile {}
}

namespace App\Models{
/**
 * App\Models\ProfileProperty
 *
 * @property integer $id
 * @property integer $skos_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $deleted_by
 * @property integer $profile_id
 * @property integer $skos_parent_id
 * @property string $name
 * @property string $label
 * @property string $definition
 * @property string $comment
 * @property string $type
 * @property string $uri
 * @property integer $status_id
 * @property string $language
 * @property string $note
 * @property integer $display_order Display order of properties
 * @property integer $export_order Display order of properties
 * @property integer $picklist_order
 * @property string $examples Link to example usage
 * @property boolean $is_required boolean -- id this value required
 * @property boolean $is_reciprocal boolean - subject and object must both have this property
 * @property boolean $is_singleton boolean -- is this property allowed to repeat for a concept
 * @property boolean $is_in_picklist boolean - is in the property picklist
 * @property boolean $is_in_export
 * @property integer $inverse_profile_property_id id of the inverse property
 * @property boolean $is_in_class_picklist boolean - is in the property picklist
 * @property boolean $is_in_property_picklist boolean - is in the property picklist
 * @property boolean $is_in_rdf boolean - should this display in the RDF
 * @property boolean $is_in_xsd boolean - should this display in the XSD
 * @property boolean $is_attribute boolean - is this an attribute? attribute's aren't editable outside the main form
 * @property boolean $has_language Boolean that determines whether language attribute is displayed for this property
 * @property boolean $is_object_prop
 * @property boolean $is_in_form
 * @property-read \App\Models\Profile $Profile
 * @property-read \App\Models\ProfileProperty $ProfilePropertyInverse
 * @property-read \App\Models\Status $Status
 * @property-read \App\Models\User $UserUpdater
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserDeletor
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProfileProperty[] $InverseProfileProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $SkosProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElement[] $ElementProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $ElementPropertyHistory
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereSkosId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereCreatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereUpdatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereDeletedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereProfileId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereSkosParentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereLabel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereDefinition($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereComment($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereDisplayOrder($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereExportOrder($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty wherePicklistOrder($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereExamples($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsRequired($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsReciprocal($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsSingleton($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInPicklist($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInExport($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereInverseProfilePropertyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInClassPicklist($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInPropertyPicklist($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInRdf($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInXsd($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsAttribute($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereHasLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsObjectProp($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ProfileProperty whereIsInForm($value)
 */
	class ProfileProperty {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_rdf_namespace table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property integer $schema_id
 * @property string $created_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property string $token
 * @property string $note
 * @property string $uri
 * @property string $schema_location
 * @property-read \App\Models\Schema $Schema
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereSchemaId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereSchemaLocation($value)
 */
	class RdfNamespace {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_skos_property table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property integer $parent_id
 * @property integer $inverse_id id of the inverse property
 * @property string $name The name of the property
 * @property string $uri The URI of the property
 * @property string $object_type the type of the object for which this is the predicate
 * @property integer $display_order Display order of properties
 * @property integer $picklist_order
 * @property string $label The pretty label for the property
 * @property string $definition
 * @property string $comment
 * @property string $examples Link to example usage
 * @property boolean $is_required boolean -- id this value required
 * @property boolean $is_reciprocal boolean - subject and object must both have this property
 * @property boolean $is_singleton boolean -- is this property allowed to repeat for a concept
 * @property boolean $is_scheme boolean - is in conceptScheme domain
 * @property boolean $is_in_picklist boolean - is in the property picklist
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistory
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereParentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereInverseId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereObjectType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereDisplayOrder($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty wherePicklistOrder($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereLabel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereDefinition($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereComment($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereExamples($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereIsRequired($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereIsReciprocal($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereIsSingleton($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereIsScheme($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\SkosProperty whereIsInPicklist($value)
 */
	class SkosProperty {}
}

namespace App\Models{
/**
 * App\Models\Status
 *
 * @property integer $id
 * @property integer $display_order
 * @property string $display_name
 * @property string $uri
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Profile[] $profiles
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProfileProperty[] $profileProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Collection[] $Collections
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Concept[] $Concepts
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $ConceptProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistory
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Schema[] $ElementSets
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaProperty[] $Elements
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElement[] $ElementProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $ElementPropertyHistory
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Vocabulary[] $Vocabularies
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Status whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Status whereDisplayOrder($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Status whereDisplayName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Status whereUri($value)
 */
	class Status {}
}

namespace App\Models{
/**
 * App\Models\User
 *
 * @property integer $id
 * @property \Carbon\Carbon $created_at
 * @property string $last_updated
 * @property \Carbon\Carbon $deleted_at
 * @property string $nickname
 * @property string $salutation
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $sha1_password
 * @property string $salt
 * @property boolean $want_to_be_moderator
 * @property boolean $is_moderator
 * @property boolean $is_administrator
 * @property integer $deletions
 * @property string $password
 * @property string $culture
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Profile[] $ProfilesUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Profile[] $ProfilesCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Profile[] $ProfilesDeleted
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProfileProperty[] $ProfilePropertiesUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProfileProperty[] $ProfilePropertiesCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ProfileProperty[] $ProfilePropertiesDeleted
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Agent[] $Agents
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Collection[] $CollectionsCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Collection[] $CollectionsUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Concept[] $ConceptsCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Concept[] $ConceptsUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $ConceptPropertiesCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $ConceptPropertiesUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistoryCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $DiscussionsCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $DiscussionsDeleted
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\FileImportHistory[] $FileImportHistory
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Schema[] $ElementSetsCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Schema[] $ElementSetsUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaProperty[] $ElementsCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaProperty[] $ElementsUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElement[] $ElementPropertiesCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElement[] $ElementPropertiesUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaPropertyElementHistory[] $ElementPropertyHistoriesCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Vocabulary[] $VocabulariesCreated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Vocabulary[] $VocabulariesUpdated
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Vocabulary[] $Vocabularies
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Schema[] $ElementSets
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\SchemaHasVersion[] $VocabularyVersionsCreated
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereLastUpdated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereNickname($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereSalutation($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereFirstName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereLastName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereEmail($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereSha1Password($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereSalt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereWantToBeModerator($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereIsModerator($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereIsAdministrator($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereDeletions($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User wherePassword($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\User whereCulture($value)
 */
	class User {}
}

namespace App\Models{
/**
 * App\Models\Vocabulary
 *
 * @property integer $id
 * @property integer $agent_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $deleted_at
 * @property \Carbon\Carbon $last_updated
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property string $child_updated_at
 * @property integer $child_updated_user_id
 * @property string $name
 * @property string $note
 * @property string $uri
 * @property string $url
 * @property string $base_domain
 * @property string $token
 * @property string $community
 * @property integer $last_uri_id
 * @property integer $status_id This will be the default status id for all concept properties for this vocabulary
 * @property string $language This is the default language for all concept properties
 * @property string $languages
 * @property integer $profile_id
 * @property string $ns_type
 * @property string $prefixes
 * @property string $repos
 * @property string $repo
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\User $UserUpdater
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $Users
 * @property-read \App\Models\Profile $profile
 * @property-read \App\Models\Agent $Agent
 * @property-read \App\Models\Status $Status
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Collection[] $Collections
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Concept[] $Concepts
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptProperty[] $ConceptProperties
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistoryObjects
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ConceptPropertyHistory[] $ConceptPropertyHistories
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Discuss[] $Discussions
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\FileImportHistory[] $FileImportHistory
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\VocabularyHasVersion[] $Versions
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereAgentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereLastUpdated($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereChildUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereChildUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereUrl($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereBaseDomain($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereCommunity($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereLastUriId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereLanguages($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereProfileId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereNsType($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary wherePrefixes($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereRepos($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Vocabulary whereRepo($value)
 */
	class Vocabulary {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_vocabulary_has_user table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property string $created_at
 * @property string $updated_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $vocabulary_id
 * @property integer $user_id
 * @property boolean $is_maintainer_for
 * @property boolean $is_registrar_for
 * @property boolean $is_admin_for
 * @property string $languages
 * @property string $default_language
 * @property string $current_language
 * @property-read \App\Models\User $User
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereIsMaintainerFor($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereIsRegistrarFor($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereIsAdminFor($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereLanguages($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereDefaultLanguage($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasUser whereCurrentLanguage($value)
 */
	class VocabularyHasUser {}
}

namespace App\Models{
/**
 * Eloquent class to describe the reg_vocabulary_has_version table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property string $name
 * @property string $created_at
 * @property \Carbon\Carbon $deleted_at
 * @property string $updated_at
 * @property integer $created_user_id
 * @property integer $vocabulary_id
 * @property \Carbon\Carbon $timeslice
 * @property-read \App\Models\User $UserCreator
 * @property-read \App\Models\Vocabulary $Vocabulary
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereVocabularyId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\VocabularyHasVersion whereTimeslice($value)
 */
	class VocabularyHasVersion {}
}

namespace App{
/**
 * App\User
 *
 */
	class User {}
}

namespace App{
/**
 * App\vocabs
 *
 */
	class vocabs {}
}

