<?php namespace App\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
/**
 * Eloquent class to describe the schema_has_user table
 *
 * automatically generated by ModelGenerator.php
 */
class ElementSetHasUser extends Model implements Transformable
{
    protected $table = 'schema_has_user';

    use SoftDeletes;
    use TransformableTrait;


    protected $dates = ['deleted_at'];

    protected $fillable = array('deleted_at', 'is_maintainer_for', 'is_registrar_for', 'is_admin_for', 'languages',
        'default_language', 'current_language');

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "id" => "integer",
        "schema_id" => "integer",
        "user_id" => "integer",
        "is_maintainer_for" => "boolean",
        "is_registrar_for" => "boolean",
        "is_admin_for" => "boolean",
        "languages" => "string",
        "default_language" => "string",
        "current_language" => "string"
    ];

    public static $rules = [
        "schema_id" => "required|",
        "user_id" => "required|",
        "languages" => "max:65535",
        "default_language" => "required|max:6",
        "current_language" => "max:6"
    ];

    public function ElementSet()
    {
        return $this->belongsTo('App\Entities\ElementSet', 'schema_id', 'id');
    }

    public function User()
    {
        return $this->belongsTo('App\Entities\User', 'user_id', 'id');
    }

}

