<?php namespace App\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
/**
 * Eloquent class to describe the schema_has_version table
 *
 * automatically generated by ModelGenerator.php
 */
class ElementSetHasVersion extends Model implements Transformable
{
    protected $table = 'schema_has_version';

    use SoftDeletes;
    use TransformableTrait;


    protected $dates = ['deleted_at', 'timeslice'];



    protected $fillable = array('name', 'deleted_at', 'timeslice');

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "id" => "integer",
        "name" => "string",
        "created_user_id" => "integer",
        "schema_id" => "integer"
    ];

    public static $rules = [
        "name" => "required|max:255"
    ];

    public function UserCreator()
    {
        return $this->belongsTo('App\Entities\User', 'created_user_id', 'id');
    }

    public function ElementSet()
    {
        return $this->belongsTo('App\Entities\ElementSet', 'schema_id', 'id');
    }

}

