<?php namespace App\Models;

/**
 * Eloquent class to describe the arc_g2t table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $g
 * @property integer $t
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcG2t whereG($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\ArcG2t whereT($value)
 */
class ArcG2t extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'arc_g2t';

    public $primaryKey = 't';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array();

}

