<?php namespace App\Models;

/**
 * Eloquent class to describe the arc_triple table
 *
 * automatically generated by ModelGenerator.php
 */
class ArcTriple extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'arc_triple';

    public $primaryKey = 't';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('s', 'p', 'o', 'o_lang_dt', 'o_comp', 's_type', 'o_type', 'misc');

}

