<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Eloquent class to describe the reg_discuss table
 *
 * automatically generated by ModelGenerator.php
 */
class Discuss extends Model
{
    protected $table = 'reg_discuss';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('deleted_at', 'uri', 'subject', 'content');

    public function UserCreayed()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function ConceptProperty()
    {
        return $this->belongsTo('App\Models\ConceptProperty', 'concept_property_id', 'id');
    }

    public function UserDeletor()
    {
        return $this->belongsTo('App\Models\User', 'deleted_user_id', 'id');
    }

    public function Schema()
    {
        return $this->belongsTo('App\Models\Schema', 'schema_id', 'id');
    }

    public function SchemaProperty()
    {
        return $this->belongsTo('App\Models\SchemaProperty', 'schema_property_id', 'id');
    }

    public function SchemaPropertyElement()
    {
        return $this->belongsTo('App\Models\SchemaPropertyElement', 'schema_property_element_id', 'id');
    }

    public function Vocabulary()
    {
        return $this->belongsTo('App\Models\Vocabulary', 'vocabulary_id', 'id');
    }

    public function Concept()
    {
        return $this->belongsTo('App\Models\Concept', 'concept_id', 'id');
    }

    public function DiscussRoot()
    {
        return $this->belongsTo('App\Models\Discuss', 'root_id', 'id');
    }

    public function DiscussParent()
    {
        return $this->belongsTo('App\Models\Discuss', 'parent_id', 'id');
    }

}

