<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the reg_rdf_namespace table
 * 
 * automatically generated by ModelGenerator.php
 *
 * @property integer $id
 * @property integer $schema_id
 * @property string $created_at
 * @property \Carbon\Carbon $deleted_at
 * @property integer $created_user_id
 * @property integer $updated_user_id
 * @property string $token
 * @property string $note
 * @property string $uri
 * @property string $schema_location
 * @property-read \App\Models\Schema $Schema
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereSchemaId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereCreatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereUpdatedUserId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereToken($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereNote($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereUri($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\RdfNamespace whereSchemaLocation($value)
 */
class RdfNamespace extends Model
{
    protected $table = 'reg_rdf_namespace';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('deleted_at', 'created_user_id', 'updated_user_id', 'token', 'note', 'uri',
        'schema_location');

    public function Schema()
    {
        return $this->belongsTo('App\Models\Schema', 'schema_id', 'id');
    }

}

