<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the reg_rdf_namespace table
 *
 * automatically generated by ModelGenerator.php
 */
class RdfNamespace extends Model
{
    protected $table = 'reg_rdf_namespace';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('deleted_at', 'created_user_id', 'updated_user_id', 'token', 'note', 'uri',
        'schema_location');

    public function Schema()
    {
        return $this->belongsTo('App\Models\Schema', 'schema_id', 'id');
    }

}

