<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the reg_agent table
 *
 * automatically generated by ModelGenerator.php
 */
class Agent extends Model
{
    protected $table = 'reg_agent';

    use SoftDeletes;

    public function getDates()
    {
        return array('last_updated', 'deleted_at');
    }

    protected $fillable = array('last_updated', 'deleted_at', 'org_email', 'org_name', 'ind_affiliation', 'ind_role',
        'address1', 'address2', 'city', 'state', 'postal_code', 'country', 'phone', 'web_address', 'type');

    public function profile()
    {
        return $this->hasMany('App\Models\Profile', 'agent_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function Users()
    {
        return $this->belongsToMany('App\Models\User', 'AgentHasUser')
            ->withPivot('is_registrar_for', 'is_admin_for')
            ->withTimestamps();
    }

    public function Schemas()
    {
        return $this->hasMany('App\Models\Schema', 'agent_id', 'id');
    }

    public function Vocabularies()
    {
        return $this->hasMany('App\Models\Vocabulary', 'agent_id', 'id');
    }

}

