<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the _agent table
 *
 * automatically generated by ModelGenerator.php
 */
class Agent extends Model
{
    protected $table = 'reg_agent';

    use SoftDeletes;

    public function getDates()
    {
        return array('last_updated', 'deleted_at');
    }

    protected $fillable = array('last_updated', 'deleted_at', 'org_email', 'org_name', 'ind_affiliation', 'ind_role',
        'address1', 'address2', 'city', 'state', 'postal_code', 'country', 'phone', 'web_address', 'type');

    public function profile()
    {
        return $this->hasMany('App\Models\Profile', 'agent_id', 'id');
    }

    public function AgentHasUser()
    {
        return $this->hasMany('App\Models\AgentHasUser', 'agent_id', 'id');
    }

    public function Schema()
    {
        return $this->hasMany('App\Models\Schema', 'agent_id', 'id');
    }

    public function Vocabulary()
    {
        return $this->hasMany('App\Models\Vocabulary', 'agent_id', 'id');
    }

}

