<?php namespace App\Models;

/**
 * Eloquent class to describe the arc_id2val table
 *
 * automatically generated by ModelGenerator.php
 */
class ArcId2val extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'arc_id2val';

    public $primaryKey = 'val_type';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('misc', 'val');

}

