<?php namespace App\Models;

/**
 * Eloquent class to describe the arc_o2val table
 *
 * automatically generated by ModelGenerator.php
 */
class ArcO2val extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'arc_o2val';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('cid', 'misc', 'val');

}

