<?php namespace App\Models;

/**
 * Eloquent class to describe the arc_setting table
 *
 * automatically generated by ModelGenerator.php
 */
class ArcSetting extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'arc_setting';

    public $primaryKey = 'k';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('val');

}

