<?php namespace App\Models;

/**
 * Eloquent class to describe the _batch table
 *
 * automatically generated by ModelGenerator.php
 */
class Batch extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_batch';

    public $timestamps = false;

    public function getDates()
    {
        return array('run_time', 'event_time');
    }

    protected $fillable = array('run_time', 'run_description', 'object_type', 'object_id', 'event_time', 'event_type',
        'event_description', 'istry_uri');

    public function FileImportHistory()
    {
        return $this->hasMany('App\Models\FileImportHistory', 'batch_id', 'id');
    }

}

