<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the _concept_property table
 *
 * automatically generated by ModelGenerator.php
 */
class ConceptProperty extends Model
{
    protected $table = 'reg_concept_property';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at', 'last_updated');
    }

    protected $fillable = array('deleted_at', 'last_updated', 'primary_pref_label', 'object', 'language',
        'is_concept_property');

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function UserUpdater()
    {
        return $this->belongsTo('App\Models\User', 'updated_user_id', 'id');
    }

    public function Concept()
    {
        return $this->belongsTo('App\Models\Concept', 'concept_id', 'id');
    }

    public function profileProperty()
    {
        return $this->belongsTo('App\Models\ProfileProperty', 'skos_property_id', 'skos_id');
    }

    public function Vocabulary()
    {
        return $this->belongsTo('App\Models\Vocabulary', 'scheme_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function RelatedConcept()
    {
        return $this->belongsTo('App\Models\Concept', 'related_concept_id', 'id');
    }

    public function PrefLabelConcept()
    {
        return $this->hasMany('App\Models\Concept', 'pref_label_id', 'id');
    }

    public function ConceptPropertyHistory()
    {
        return $this->hasMany('App\Models\ConceptPropertyHistory', 'concept_property_id', 'id');
    }

    public function Discuss()
    {
        return $this->hasMany('App\Models\Discuss', 'concept_property_id', 'id');
    }

}

