<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Eloquent class to describe the _concept table
 *
 * automatically generated by ModelGenerator.php
 */
class Concept extends Model
{
    protected $table = 'reg_concept';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at', 'last_updated');
    }

    protected $fillable = array('deleted_at', 'last_updated', 'uri', 'pref_label', 'is_top_concept', 'language');

    public function Vocabulary()
    {
        return $this->belongsTo('App\Models\Vocabulary', 'vocabulary_id', 'id');
    }

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function PrefLabelConceptProperty()
    {
        return $this->belongsTo('App\Models\ConceptProperty', 'pref_label_id', 'id');
    }

    public function UserUpdater()
    {
        return $this->belongsTo('App\Models\User', 'updated_user_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function ConceptProperty()
    {
        return $this->hasMany('App\Models\ConceptProperty', 'concept_id', 'id');
    }

    public function RelatedConceptProperty()
    {
        return $this->hasMany('App\Models\ConceptProperty', 'related_concept_id', 'id');
    }

    public function RelatedConceptPropertyHistory()
    {
        return $this->hasMany('App\Models\ConceptPropertyHistory', 'related_concept_id', 'id');
    }

    public function ConceptPropertyHistory()
    {
        return $this->hasMany('App\Models\ConceptPropertyHistory', 'concept_id', 'id');
    }

    public function Discuss()
    {
        return $this->hasMany('App\Models\Discuss', 'concept_id', 'id');
    }

}

