<?php namespace App\Models;

/**
 * Eloquent class to describe the reg_concept_property_history table
 *
 * automatically generated by ModelGenerator.php
 */
class ConceptPropertyHistory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_concept_property_history';

    public function getDates()
    {
        return array('action');
    }

    protected $fillable = array('action', 'object', 'language', 'change_note');

    public function SkosProperty()
    {
        return $this->belongsTo('App\Models\SkosProperty', 'skos_property_id', 'id');
    }

    public function FileImportHistory()
    {
        return $this->belongsTo('App\Models\FileImportHistory', 'import_id', 'id');
    }

    public function ObjectScheme()
    {
        return $this->belongsTo('App\Models\Vocabulary', 'scheme_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function ObjectConcept()
    {
        return $this->belongsTo('App\Models\Concept', 'related_concept_id', 'id');
    }

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function ConceptProperty()
    {
        return $this->belongsTo('App\Models\ConceptProperty', 'concept_property_id', 'id');
    }

    public function Vocabulary()
    {
        return $this->belongsTo('App\Models\Vocabulary', 'vocabulary_id', 'id');
    }

    public function Concept()
    {
        return $this->belongsTo('App\Models\Concept', 'concept_id', 'id');
    }

}

