<?php namespace App\Models;

/**
 * Eloquent class to describe the _prefix table
 *
 * automatically generated by ModelGenerator.php
 */
class Prefix extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_prefix';

    public $primaryKey = 'prefix';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('uri', 'rank');

}

