<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the profile_property table
 *
 * automatically generated by ModelGenerator.php
 */
class ProfileProperty extends Model
{
    protected $table = 'profile_property';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('skos_id', 'deleted_at', 'skos_parent_id', 'name', 'label', 'definition', 'comment',
        'type', 'uri', 'language', 'note', 'display_order', 'export_order', 'picklist_order', 'examples', 'is_required',
        'is_reciprocal', 'is_singleton', 'is_in_picklist', 'is_in_export', 'is_in_class_picklist', 'is_in_property_picklist',
        'is_in_rdf', 'is_in_xsd', 'is_attribute', 'has_language', 'is_object_prop', 'is_in_form');

    public function Profile()
    {
        return $this->belongsTo('App\Models\Profile', 'profile_id', 'id');
    }

    public function ProfilePropertyInverse()
    {
        return $this->belongsTo('App\Models\ProfileProperty', 'inverse_profile_property_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function UserUpdater()
    {
        return $this->belongsTo('App\Models\User', 'updated_by', 'id');
    }

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_by', 'id');
    }

    public function UserDeletor()
    {
        return $this->belongsTo('App\Models\User', 'deleted_by', 'id');
    }

    public function profileProperty()
    {
        return $this->hasMany('App\Models\ProfileProperty', 'inverse_profile_property_id', 'id');
    }

    public function ConceptProperty()
    {
        return $this->hasMany('App\Models\ConceptProperty', 'skos_property_id', 'skos_id');
    }

    public function SchemaPropertyElement()
    {
        return $this->hasMany('App\Models\SchemaPropertyElement', 'profile_property_id', 'id');
    }

    public function SchemaPropertyElementHistory()
    {
        return $this->hasMany('App\Models\SchemaPropertyElementHistory', 'profile_property_id', 'id');
    }

}

