<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Eloquent class to describe the profile table
 *
 * automatically generated by ModelGenerator.php
 */
class Profile extends Model
{
    protected $table = 'profile';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('deleted_at', 'name', 'note', 'uri', 'url', 'base_domain', 'token',
        'community', 'last_uri_id', 'language');

    public function Agent()
    {
        return $this->belongsTo('App\Models\Agent', 'agent_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function UserUpdater()
    {
        return $this->belongsTo('App\Models\User', 'updated_by', 'id');
    }

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_by', 'id');
    }

    public function UserDeletor()
    {
        return $this->belongsTo('App\Models\User', 'deleted_by', 'id');
    }

    public function profileProperties()
    {
        return $this->hasMany('App\Models\ProfileProperty', 'profile_id', 'id');
    }

    public function Schemas()
    {
        return $this->hasMany('App\Models\Schema', 'profile_id', 'id');
    }

    public function Vocabularies()
    {
        return $this->hasMany('App\Models\Vocabulary', 'profile_id', 'id');
    }

}

