<?php namespace App\Models;

/**
 * Eloquent class to describe the _schema table
 *
 * automatically generated by ModelGenerator.php
 */
class Schema extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_schema';

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('deleted_at', 'name', 'note', 'uri', 'url',
        'base_domain', 'token', 'community', 'last_uri_id', 'language', 'ns_type', 'prefixes', 'languages', 'repo');

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function UserUpdater()
    {
        return $this->belongsTo('App\Models\User', 'updated_user_id', 'id');
    }

    public function Agent()
    {
        return $this->belongsTo('App\Models\Agent', 'agent_id', 'id');
    }

    public function profile()
    {
        return $this->belongsTo('App\Models\Profile', 'profile_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function Discuss()
    {
        return $this->hasMany('App\Models\Discuss', 'schema_id', 'id');
    }

    public function FileImportHistory()
    {
        return $this->hasMany('App\Models\FileImportHistory', 'schema_id', 'id');
    }

    public function RdfNamespace()
    {
        return $this->hasMany('App\Models\RdfNamespace', 'schema_id', 'id');
    }

    public function SchemaProperty()
    {
        return $this->hasMany('App\Models\SchemaProperty', 'schema_id', 'id');
    }

    public function SchemaPropertyElementHistory()
    {
        return $this->hasMany('App\Models\SchemaPropertyElementHistory', 'schema_id', 'id');
    }

    public function schemaHasUser()
    {
        return $this->hasMany('App\Models\SchemaHasUser', 'schema_id', 'id');
    }

    public function schemaHasVersion()
    {
        return $this->hasMany('App\Models\SchemaHasVersion', 'schema_id', 'id');
    }

}

