<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the reg_schema_property_element table
 *
 * automatically generated by ModelGenerator.php
 */
class SchemaPropertyElement extends Model
{
    protected $table = 'reg_schema_property_element';

    use SoftDeletes;

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('deleted_at', 'is_schema_property', 'object', 'language', 'is_generated');

    public function profileProperty()
    {
        return $this->belongsTo('App\Models\ProfileProperty', 'profile_property_id', 'id');
    }

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function UserUpdater()
    {
        return $this->belongsTo('App\Models\User', 'updated_user_id', 'id');
    }

    public function SchemaProperty()
    {
        return $this->belongsTo('App\Models\SchemaProperty', 'schema_property_id', 'id');
    }

    public function RelatedSchemaProperty()
    {
        return $this->belongsTo('App\Models\SchemaProperty', 'related_schema_property_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function Discuss()
    {
        return $this->hasMany('App\Models\Discuss', 'schema_property_element_id', 'id');
    }

    public function SchemaPropertyElementHistory()
    {
        return $this->hasMany('App\Models\SchemaPropertyElementHistory', 'schema_property_element_id', 'id');
    }

}

