<?php namespace App\Models;

/**
 * Eloquent class to describe the _schema_property_element_history table
 *
 * automatically generated by ModelGenerator.php
 */
class SchemaPropertyElementHistory extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_schema_property_element_history';

    public function getDates()
    {
        return array('action');
    }

    protected $fillable = array('action', 'object', 'language', 'change_note');

    public function UserCreator()
    {
        return $this->belongsTo('App\Models\User', 'created_user_id', 'id');
    }

    public function SchemaPropertyElement()
    {
        return $this->belongsTo('App\Models\SchemaPropertyElement', 'schema_property_element_id', 'id');
    }

    public function SchemaProperty()
    {
        return $this->belongsTo('App\Models\SchemaProperty', 'schema_property_id', 'id');
    }

    public function Schema()
    {
        return $this->belongsTo('App\Models\Schema', 'schema_id', 'id');
    }

    public function RelatedSchemaProperty()
    {
        return $this->belongsTo('App\Models\SchemaProperty', 'related_schema_property_id', 'id');
    }

    public function Status()
    {
        return $this->belongsTo('App\Models\Status', 'status_id', 'id');
    }

    public function profileProperty()
    {
        return $this->belongsTo('App\Models\ProfileProperty', 'profile_property_id', 'id');
    }

    public function FileImportHistory()
    {
        return $this->belongsTo('App\Models\FileImportHistory', 'import_id', 'id');
    }

}

