<?php namespace App\Models;

/**
 * Eloquent class to describe the _skos_property table
 *
 * automatically generated by ModelGenerator.php
 */
class SkosProperty extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_skos_property';

    public $timestamps = false;

    protected $fillable = array('parent_id', 'inverse_id', 'name', 'uri', 'object_type', 'display_order',
        'picklist_order', 'label', 'definition', 'comment', 'examples', 'is_required', 'is_reciprocal', 'is_singleton',
        'is_scheme', 'is_in_picklist');

    public function ConceptPropertyHistory()
    {
        return $this->hasMany('App\Models\ConceptPropertyHistory', 'skos_property_id', 'id');
    }

}

