<?php namespace App\Models;

/**
 * Eloquent class to describe the reg_status table
 *
 * automatically generated by ModelGenerator.php
 */
class Status extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'reg_status';

    public $timestamps = false;

    protected $fillable = array('display_order', 'display_name', 'uri');

    public function profile()
    {
        return $this->hasMany('App\Models\Profile', 'status_id', 'id');
    }

    public function profileProperty()
    {
        return $this->hasMany('App\Models\ProfileProperty', 'status_id', 'id');
    }

    public function Collection()
    {
        return $this->hasMany('App\Models\Collection', 'status_id', 'id');
    }

    public function Concept()
    {
        return $this->hasMany('App\Models\Concept', 'status_id', 'id');
    }

    public function ConceptProperty()
    {
        return $this->hasMany('App\Models\ConceptProperty', 'status_id', 'id');
    }

    public function ConceptPropertyHistory()
    {
        return $this->hasMany('App\Models\ConceptPropertyHistory', 'status_id', 'id');
    }

    public function Schema()
    {
        return $this->hasMany('App\Models\Schema', 'status_id', 'id');
    }

    public function SchemaProperty()
    {
        return $this->hasMany('App\Models\SchemaProperty', 'status_id', 'id');
    }

    public function SchemaPropertyElement()
    {
        return $this->hasMany('App\Models\SchemaPropertyElement', 'status_id', 'id');
    }

    public function SchemaPropertyElementHistory()
    {
        return $this->hasMany('App\Models\SchemaPropertyElementHistory', 'status_id', 'id');
    }

    public function Vocabulary()
    {
        return $this->hasMany('App\Models\Vocabulary', 'status_id', 'id');
    }

}

