<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Eloquent class to describe the _user table
 *
 * automatically generated by ModelGenerator.php
 */
class User extends Model
{
    protected $table = 'reg_user';

    use SoftDeletes;

    public function getDates()
    {
        return array('last_updated', 'deleted_at');
    }

    protected $fillable = array('last_updated', 'deleted_at', 'nickname', 'salutation', 'first_name', 'last_name',
        'email', 'sha1_password', 'salt', 'want_to_be_moderator', 'is_moderator', 'is_administrator', 'deletions', 'password',
        'culture');

    public function ProfileUpdated()
    {
        return $this->hasMany('App\Models\Profile', 'updated_by', 'id');
    }

    public function ProfileCreated()
    {
        return $this->hasMany('App\Models\Profile', 'created_by', 'id');
    }

    public function ProfileDeleted()
    {
        return $this->hasMany('App\Models\Profile', 'deleted_by', 'id');
    }

    public function ProfilePropertyUpdated()
    {
        return $this->hasMany('App\Models\ProfileProperty', 'updated_by', 'id');
    }

    public function ProfilePropertyCreated()
    {
        return $this->hasMany('App\Models\ProfileProperty', 'created_by', 'id');
    }

    public function ProfilePropertyDeleted()
    {
        return $this->hasMany('App\Models\ProfileProperty', 'deleted_by', 'id');
    }

    public function AgentHasUser()
    {
        return $this->hasMany('App\Models\AgentHasUser', 'user_id', 'id');
    }

    public function CollectionCreated()
    {
        return $this->hasMany('App\Models\Collection', 'created_user_id', 'id');
    }

    public function CollectionUpdated()
    {
        return $this->hasMany('App\Models\Collection', 'updated_user_id', 'id');
    }

    public function ConceptCreated()
    {
        return $this->hasMany('App\Models\Concept', 'created_user_id', 'id');
    }

    public function ConceptUpdated()
    {
        return $this->hasMany('App\Models\Concept', 'updated_user_id', 'id');
    }

    public function ConceptPropertyCreated()
    {
        return $this->hasMany('App\Models\ConceptProperty', 'created_user_id', 'id');
    }

    public function ConceptPropertyUpdated()
    {
        return $this->hasMany('App\Models\ConceptProperty', 'updated_user_id', 'id');
    }

    public function ConceptPropertyHistoryCreated()
    {
        return $this->hasMany('App\Models\ConceptPropertyHistory', 'created_user_id', 'id');
    }

    public function DiscussCreated()
    {
        return $this->hasMany('App\Models\Discuss', 'created_user_id', 'id');
    }

    public function DiscussDeleted()
    {
        return $this->hasMany('App\Models\Discuss', 'deleted_user_id', 'id');
    }

    public function FileImportHistory()
    {
        return $this->hasMany('App\Models\FileImportHistory', 'user_id', 'id');
    }

    public function SchemaCreated()
    {
        return $this->hasMany('App\Models\Schema', 'created_user_id', 'id');
    }

    public function SchemaUpdated()
    {
        return $this->hasMany('App\Models\Schema', 'updated_user_id', 'id');
    }

    public function SchemaPropertyCreated()
    {
        return $this->hasMany('App\Models\SchemaProperty', 'created_user_id', 'id');
    }

    public function SchemaPropertyUpdated()
    {
        return $this->hasMany('App\Models\SchemaProperty', 'updated_user_id', 'id');
    }

    public function SchemaPropertyElementCreated()
    {
        return $this->hasMany('App\Models\SchemaPropertyElement', 'created_user_id', 'id');
    }

    public function SchemaPropertyElementUpdated()
    {
        return $this->hasMany('App\Models\SchemaPropertyElement', 'updated_user_id', 'id');
    }

    public function SchemaPropertyElementHistoryCreated()
    {
        return $this->hasMany('App\Models\SchemaPropertyElementHistory', 'created_user_id', 'id');
    }

    public function VocabularyCreated()
    {
        return $this->hasMany('App\Models\Vocabulary', 'created_user_id', 'id');
    }

    public function VocabularyUpdated()
    {
        return $this->hasMany('App\Models\Vocabulary', 'updated_user_id', 'id');
    }

    public function Vocabulary()
    {
        return $this->hasMany('App\Models\Vocabulary', 'child_updated_user_id', 'id');
    }

    public function VocabularyHasVersionCreated()
    {
        return $this->hasMany('App\Models\VocabularyHasVersion', 'created_user_id', 'id');
    }

    public function SchemaHasUser()
    {
        return $this->hasMany('App\Models\SchemaHasUser', 'user_id', 'id');
    }

    public function SchemaHasVersionCreated()
    {
        return $this->hasMany('App\Models\SchemaHasVersion', 'created_user_id', 'id');
    }

}

